# PostgreSQL. Versions 8.2 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: chasingb_dev
  host: localhost

test:
  <<: *default
  database: chasingb_test
  host: localhost

production:
  <<: *default
  database: chasingb_pro
